apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: k8s
  region: us-east-1

availabilityZones: ["us-east-1a", "us-east-1b"]

managedNodeGroups:
  - name: spot-us-east-1a
    instanceTypes: ["c4.large", "c4.xlarge", "c5.large", "c5.xlarge"]
    spot: true
    availabilityZones: ["us-east-1a"]
    minSize: 1
    maxSize: 10
    desiredCapacity: 2
